import { Timestamp } from "firebase/firestore";
import { PlayerEpisode } from "./episodes";

export interface Chat {
  id: string; // Firestore Document ID
  chat_id: string; // Chat ID
  user_id: string; // User ID
  sender: string; // Sender
  chat_text: string; // Chat Text
  conversation_id: string; // Conversation ID for LLM
  podcast_data?: PlayerEpisode; // Store podcast data for podcast messages
  created_at: Date | null;  // updated by the database service
  updated_at: Date | null;  // updated by the database service
  deleted_at: Date | null;  // updated by the database service
  is_deleted: boolean | false; // Is Deleted
}

export type ChatMessage = { // Message type for chat history
  id?: string;
  uid?: string;
  conversation_id?: string;
  content: string;
  sender: "user" | "assistant" | "podcast" | "system";
  timestamp: Date | Timestamp;
  player_episode?: PlayerEpisode;
};

export type ChatMessageResponse = {
  id: string;
  uid?: string;
  conversation_id?: string;
  content: string;
  sender: string;
  timestamp: Timestamp;
};

// Helper function to convert Firestore data to Chat type
export function convertToChat(data: any): Chat {
  return {
    id: data.id,     // Firestore Document ID (generated by the database service)
    chat_id: data.id,
    user_id: data.uid,
    sender: data.sender || "user",
    chat_text: data.content || "",
    conversation_id: data.conversation_id || null,
    podcast_data: data.player_episode || null,
    deleted_at: data.deleted_at?.toDate() || null, // updated by the database service
    created_at: data.timestamp?.toDate() || null,  // updated by the database service
    updated_at: data.timestamp?.toDate() || null,  // updated by the database service
    is_deleted: data.is_deleted || false,
  };
}